MESSAGES = global.level_list[global.ACTIVE_LEVEL].chatdata.script
show_debug_message(array_length(MESSAGES))
DRAWN_MESSAGE = ""

CHAR_DELAY = 1
SCROLL_FINISHED = false
CURRENT_CHAR = 0
CURRENT_MESSAGE = 0
CHARS = -1
CHAR_TIMER = 0

ACTION = false

CURSORDELAY = 5
CURSORTIMER = 0
CURSORINDEX = 0

SPECIAL_CHARS = [ "*" ]
SPECIAL_WAIT = 0

DO_TEXT_SOUND = true

EXPRESSION_FRAME = 0
EXPRESSION_TIMER = 0